# For more information: https://laravel.com/docs/laravel
version: '3'
services:
  ofelia:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - jumia
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - jumia
    depends_on:
      - web
      - mariadb
  beanstalkd:
    image: schickling/beanstalkd
    restart: always
    ports:
      - '11300:11300'
    depends_on:
      - web
    networks:
      - jumia
  web:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: jumia_app
    restart: unless-stopped
    ports:
      - '9001:9000'
    depends_on:
      - mariadb
      - ofelia
    networks:
      - jumia
    labels:
      ofelia.enabled: 'true'
      ofelia.job-exec.queue.schedule: '@every 5s'
      ofelia.job-exec.queue.command: 'php artisan queue:work'
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx-5dmat-web
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - web
      - mariadb
    networks:
      - jumia
  mariadb:
    image: mariadb
    container_name: jumia_mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: homestead
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './mariadb:/var/lib/mysql'
    networks:
      - jumia
networks:
  jumia:
    driver: bridge
